### ISSUE TITLE
1.4 - Crash when key press in menu

### ISSUE THREAD

**Issue by kiwiphoenix364** [damqn4etoBG/Endless-Expansion-1.20.1#1]
Trying to add this to my modpack, and an issue I've come across is that when I type in a menu when not loaded into a world the game crashes. This includes searching for a mod in the mods list, typing in a server menu, and any other place where you'd input/manipulate text, the game instantly crashes. I also tested 1.31, and it does not have this same issue. Crash report is below:
[crash-2024-08-08_14.30.24-client.txt](https://github.com/user-attachments/files/16552276/crash-2024-08-08_14.30.24-client.txt)

Very cool mod by the way, hope this is an issue that can be resolved!

**Comment by kiwiphoenix364** [comment]
Actually it turns out it doesn't matter if it's a text box, just pressing any key in general causes the crash. Weird bug

**Comment by protoknight12** [comment]
Will get on fixing that rn

**Comment by damqn4etoBG** [comment]
We'll look into this right now

**Comment by protoknight12** [comment]
We are glad to see that you like the mod, so we'll do whats possible to fix

**Comment by damqn4etoBG** [comment]
I believe we fixed this exact issue at the start of developing 1.5, because 1.5 turns the dash system into a capability and this issue does not arrise. 1.5 will be released today or tomorrow.
